version: '3.5'

volumes:
  futurespacedb:
  redis-data:

networks:
  default:
    driver: bridge
    name: futurespaceweb

services:
  postgresql:
    image: "postgres:16.1"
    hostname: postgresql
    container_name: postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 10s
    volumes:
      - ./Infrastructure/Persistence/Migrations/migrations.sql:/migrations/migrations.sql:ro
      - ./Infrastructure/Persistence/Migrations/Launch.data/spacedevs_data.sql:/migrations/seed/spacedevs_data.sql:ro
      - ./Infrastructure/Persistence/Migrations/Launch.data/seeddatabase.sh:/docker-entrypoint-initdb.d/seeddatabase.sh:ro
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=futurespacedb

  redis:
    image: "redis:7.2.5"
    hostname: redis
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: ["redis-server", "--appendonly", "yes"]

  api:
    build:
      context: .
      dockerfile: dockerfile
    hostname: api
    container_name: api
    depends_on:
      - postgresql
      - redis
    environment:
      - POSTGRESQL_CONNECTION_STRING=Host=postgresql;Username=root;Password=root;Database=futurespacedb;Connection Pruning Interval=1;Connection Idle Lifetime=2;Enlist=false;No Reset On Close=true;MinPoolSize=1;MaxPoolSize=1024;Include Error Detail=True
      - REDIS_CONNECTION_STRING=redis:6379
      - ASPNETCORE_URLS=http://+:5000

  nginx:
    image: "nginx:1.25.5"
    command: ["nginx", "-g", "daemon off;"]
    container_name: nginx
    depends_on:
      - api
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "7000:7000"
    expose:
      - "7000"
