version: '3.5'

volumes:
  baseapidb:

networks:
  default:
    driver: bridge
    name: baseapiweb

services:
  postgresql:
    image: "postgres:16.1"
    hostname: postgresql
    container_name: postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 10s
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=baseapidb

  api:
    build:
      context: .
      dockerfile: dockerfile
    hostname: api
    container_name: api
    depends_on:
      - postgresql
    environment:
      - POSTGRESQL_CONNECTION_STRING=Host=postgresql;Username=root;Password=root;Database=futurespacedb;Connection Pruning Interval=1;Connection Idle Lifetime=2;Enlist=false;No Reset On Close=true;MinPoolSize=1;MaxPoolSize=1024;Include Error Detail=True
      - ASPNETCORE_URLS=http://+:5000

  nginx:
    image: "nginx:1.25.5"
    command: ["nginx", "-g", "daemon off;"]
    container_name: nginx
    depends_on:
      - api
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "7000:7000"
    expose:
      - "7000"