name: CI
on:
  push:
    branches: ["master"]
  workflow_dispatch:

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - name: Get the code
        uses: actions/checkout@v4.1.3
        
      - name: Install .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0'
          
      - name: Restore dependencies
        run: dotnet restore

      - name: Build the project
        run: dotnet build --configuration Release

      - name: Run xUnit tests
        run: dotnet test --configuration Release --no-build
      
      - name: Docker Auth
        uses: docker/login-action@v3.1.0
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PWD }}

      - name: Second step, build and push Docker images
        uses: docker/build-push-action@v5.3.0
        with:
          context: .
          file: ./dockerfile
          push: true
          tags:
            raphsodyz/FutureSpaceTheSpacedevs:${{ github.run_number }}
            raphsodyz/FutureSpaceTheSpacedevs:latest
